/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/fta/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fta Query
         * @description Answers an FTA question from the sourced corpus, or escalates.
         *
         *     A query with no confirmed corpus match is **not** an error: it returns HTTP 200 with
         *     `status: "no_match"` and the Action Required escalation path. Returning 404 would push
         *     callers toward an error branch that discards the guidance.
         */
        get: operations["fta_query_api_fta_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for the host's health check (ADR-0004).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionRequiredOut
         * @description The escalation state. Carries no topic, treatment or citation, by design.
         */
        ActionRequiredOut: {
            /** Message */
            message: string;
            /** Next Step */
            next_step: string;
            /** Escalation Path */
            escalation_path: string;
            /** Status Line */
            status_line: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Disclaimer */
            disclaimer: string;
            /** Confidence */
            confidence: string;
            /** Confidence Meaning */
            confidence_meaning: string;
        };
        /**
         * AnswerOut
         * @description A sourced FTA finding. Every field is evidence or the presentation it must carry.
         */
        AnswerOut: {
            /** Topic */
            topic: string;
            /** Sector */
            sector: string;
            /** Treatment */
            treatment: string;
            /** Confirmed */
            confirmed: boolean;
            /** Citation */
            citation: string;
            /**
             * Verified At
             * Format: date
             */
            verified_at: string;
            /** Status Line */
            status_line: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Next Step */
            next_step: string;
            /** Disclaimer */
            disclaimer: string;
            /** Confidence */
            confidence: string;
            /** Confidence Meaning */
            confidence_meaning: string;
            /** Notes */
            notes?: string | null;
        };
        /**
         * FtaQueryResponse
         * @description `status` is the field a client branches on — not the length of `answers`.
         *
         *     A client that only checked `answers` would render an empty results list for a no-match and
         *     silently drop the escalation path, which is the outcome docs/modules/fta-centre.md exists to
         *     prevent.
         */
        FtaQueryResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "matched" | "no_match";
            /** Query */
            query: string;
            /** Answers */
            answers: components["schemas"]["AnswerOut"][];
            action_required?: components["schemas"]["ActionRequiredOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    fta_query_api_fta_query_get: {
        parameters: {
            query: {
                /** @description A sector or product question, e.g. 'dairy' or 'manuka honey'. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FtaQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
