/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Draft -> Run Authorised. Launch authority; human gated (run-level, #227).
         */
        post: operations["start_run_api_runs__run_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Run
         * @description Awaiting CEO Decision -> Paused. CEO decision; `approval_ref` must name a
         *     `decision_records` row.
         */
        post: operations["pause_run_api_runs__run_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Run
         * @description Paused -> Coverage Locked. Resumption authority; human gated (run-level, #227).
         */
        post: operations["resume_run_api_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/fail-qa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fail Qa
         * @description QA in Progress -> QA Failed. The Quality Reviewer's stop.
         *
         *     REQ-U-01: "A Critical failure blocks progression to the CEO decision." This is that block,
         *     and it is the reviewer's independent authority: it is the one lifecycle move they can make
         *     without the SIP Owner, and it prevents a brief they consider unsound from reaching the CEO at
         *     all. Without this route the reviewer could record findings and still had no way to stop the
         *     run, which made the QA gate advisory.
         *
         *     Deliberately not `Stopped`. REQ-U-02 reserves Stop for the CEO decision screen, so a reviewer
         *     who terminates the run outright would be taking a decision the requirements give to the CEO.
         *     QA Failed routes back to Report Drafted for correction, which is the documented path.
         */
        post: operations["fail_qa_api_runs__run_id__fail_qa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Run
         * @description Awaiting CEO Decision -> Stopped. Terminal, and the CEO's decision alone.
         *
         *     REQ-U-02 lists the CEO's four options as Continue, Continue with Correction, Pause and Stop.
         *     Pause was mounted and Stop was not, so the only terminal refusal in the state machine had no
         *     way to be exercised: a run the CEO wanted stopped could only be paused, which says something
         *     different and leaves it resumable.
         *
         *     `Stopped` has no outbound transitions. Human gated, so `approval_ref` must name the
         *     `decision_records` row carrying the decision.
         */
        post: operations["stop_run_api_runs__run_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Run
         * @description Distributed -> Closed. Mechanical closeout; not human gated.
         */
        post: operations["complete_run_api_runs__run_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Run Audit
         * @description The run's audit trail, newest first. Every staff role may read it.
         *
         *     **Readable by all seven roles deliberately.** An audit trail nobody can read is not an audit
         *     trail, and the Auditor and Board Viewer roles exist precisely to read it. Restricting it to the
         *     owner would mean the person most likely to be audited controls who sees the record.
         *
         *     **404 for an unknown run, not an empty page.** A run with no audit rows cannot exist, because
         *     `create_run` writes one in the same transaction, so an empty result means the run id is wrong
         *     and saying so is more useful than returning `[]`. The run is looked up first for that reason.
         *
         *     Ordered by `id`, so rows written in one transaction keep their real order: `at` is transaction
         *     start time and would tie.
         */
        get: operations["read_run_audit_api_runs__run_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates */
        get: operations["list_candidates_api_candidates_get"];
        put?: never;
        /** Capture Candidate */
        post: operations["capture_candidate_api_candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate */
        get: operations["get_candidate_api_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Candidate */
        post: operations["verify_candidate_api_candidates__candidate_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Candidate */
        post: operations["score_candidate_api_candidates__candidate_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Candidate */
        post: operations["route_candidate_api_candidates__candidate_id__route_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Merge Candidate */
        post: operations["merge_candidate_api_candidates__candidate_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comms/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft
         * @description Generates a draft. Never sends or publishes anything - see `apps/comms/draft.py`'s module
         *     docstring for why "nothing publishable without a recorded reviewer" holds by construction.
         *
         *     Failure mapping is deliberately specific, not a blanket 500:
         *     - `GatewayNotConfiguredError` / `RedactionNotConfiguredError` -> 503. Deployment configuration
         *       is missing (no API key, or - per ADR-0006 - no approved `REDACTION_POLICY_PATH`). Expected,
         *       correct refusal in any environment that hasn't been configured yet, not a bug to alert on
         *       the same way as a real failure.
         *     - `GatewayCallError` -> 502. The provider call itself failed after a retry - genuinely down,
         *       distinct from "not configured".
         */
        post: operations["draft_api_comms_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Who the current session belongs to, and the CSRF token to send with writes.
         *
         *     A UI needs this to know which controls to show. It is not the authorisation check: the server
         *     re-checks on every write, because a hidden button is a hint and not a control.
         */
        get: operations["whoami_api_session_get"];
        put?: never;
        post?: never;
        /**
         * Sign Out
         * @description Ends the session server-side and clears the cookie.
         *
         *     Deliberately not behind the CSRF check. A forged sign-out is a nuisance rather than a breach,
         *     and refusing to sign someone out because a token was missing is the worse failure.
         */
        delete: operations["sign_out_api_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin Github Sign In
         * @description Starts the handshake: mint a state value, set it as a cookie, redirect to GitHub.
         */
        get: operations["begin_github_sign_in_api_auth_github_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete Github Sign In
         * @description Completes the handshake and issues a session, or refuses.
         *
         *     Checked in this order, and the order is the point: the state before the code, because
         *     validating an attacker-supplied code first would mean exchanging it with GitHub before
         *     discovering the request was forged.
         */
        get: operations["complete_github_sign_in_api_auth_github_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fta/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fta Query
         * @description Answers an FTA question from the sourced corpus, or escalates.
         *
         *     A query with no confirmed corpus match is **not** an error: it returns HTTP 200 with
         *     `status: "no_match"` and the Action Required escalation path. Returning 404 would push
         *     callers toward an error branch that discards the guidance.
         */
        get: operations["fta_query_api_fta_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for the host's health check (ADR-0004).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionRequiredOut
         * @description The escalation state. Carries no topic, treatment or citation, by design.
         */
        ActionRequiredOut: {
            /** Message */
            message: string;
            /** Next Step */
            next_step: string;
            /** Escalation Path */
            escalation_path: string;
            /** Status Line */
            status_line: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Disclaimer */
            disclaimer: string;
            /** Confidence */
            confidence: string;
            /** Confidence Meaning */
            confidence_meaning: string;
        };
        /**
         * AnswerOut
         * @description A sourced FTA finding. Every field is evidence or the presentation it must carry.
         */
        AnswerOut: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /** Sector */
            sector: string;
            /** Treatment */
            treatment: string;
            /** Confirmed */
            confirmed: boolean;
            /** Citation */
            citation: string;
            /**
             * Verified At
             * Format: date
             */
            verified_at: string;
            /** Status Line */
            status_line: string;
            /** Jurisdiction */
            jurisdiction: string;
            /** Next Step */
            next_step: string;
            /** Disclaimer */
            disclaimer: string;
            /** Confidence */
            confidence: string;
            /** Confidence Meaning */
            confidence_meaning: string;
            /** Notes */
            notes?: string | null;
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Id */
            id: number;
            /** At */
            at: string;
            /** User Id */
            user_id: string | null;
            /** Action */
            action: string;
            /** Record Type */
            record_type: string | null;
            /** Record Id */
            record_id: string | null;
            /** Old Value */
            old_value: string | null;
            /** New Value */
            new_value: string | null;
            /** Reason */
            reason: string | null;
            /** Approval Ref */
            approval_ref: string | null;
        };
        /**
         * AuditPageOut
         * @description A page of audit entries plus the cursor for the next one.
         *
         *     `next_before_id` rather than a page number, so a caller pages by passing back what it was
         *     given instead of computing an offset. `null` means this is the last page.
         */
        AuditPageOut: {
            /** Entries */
            entries: components["schemas"]["AuditEntryOut"][];
            /** Next Before Id */
            next_before_id: number | null;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Id */
            id: string;
            /** Run Id */
            run_id: string;
            /** Headline */
            headline: string;
            /** Source Id */
            source_id: string | null;
            /** Url */
            url: string | null;
            /** Summary */
            summary: string | null;
            /** Published At */
            published_at: string | null;
            /** Captured At */
            captured_at: string;
            /** In Coverage Window */
            in_coverage_window: boolean | null;
            /** Nz Relevance */
            nz_relevance: number | null;
            /** India Relevance */
            india_relevance: number | null;
            /** Member Relevance */
            member_relevance: number | null;
            /** Signal */
            signal: string | null;
            /** Confidence */
            confidence: string | null;
            /** Verification */
            verification: string;
            /** Duplicate Of */
            duplicate_of: string | null;
            /** Included */
            included: boolean | null;
            /** Reason */
            reason: string | null;
            /** Proposed Routing */
            proposed_routing: string | null;
        };
        /** CaptureCandidateIn */
        CaptureCandidateIn: {
            /** Run Id */
            run_id: string;
            /** Headline */
            headline: string;
            /** Source Id */
            source_id?: string | null;
            /** Url */
            url?: string | null;
            /** Summary */
            summary?: string | null;
            /** Published At */
            published_at?: string | null;
            /** In Coverage Window */
            in_coverage_window?: boolean | null;
        };
        /** CreateRunIn */
        CreateRunIn: {
            /** Run Number */
            run_number: string;
            /** Prompt Version */
            prompt_version: string;
            /** Coverage Start Utc */
            coverage_start_utc: string;
            /** Coverage End Utc */
            coverage_end_utc: string;
        };
        /** DraftIn */
        DraftIn: {
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "newsletter" | "linkedin_post" | "event_announcement" | "member_spotlight";
            /** Brief */
            brief: string;
        };
        /**
         * DraftOut
         * @description Matches `apps/comms/ui/src/api/client.ts`'s `isCommsDraftResult` guard exactly: one
         *     required non-empty `draft` string, nothing else the UI reads today.
         */
        DraftOut: {
            /** Draft */
            draft: string;
        };
        /**
         * FtaQueryResponse
         * @description `status` is the field a client branches on — not the length of `answers`.
         *
         *     A client that only checked `answers` would render an empty results list for a no-match and
         *     silently drop the escalation path, which is the outcome docs/modules/fta-centre.md exists to
         *     prevent.
         */
        FtaQueryResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "matched" | "no_match";
            /** Query */
            query: string;
            /** Answers */
            answers: components["schemas"]["AnswerOut"][];
            action_required?: components["schemas"]["ActionRequiredOut"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MergeIn */
        MergeIn: {
            /** Duplicate Of */
            duplicate_of: string;
            /** Reason */
            reason: string;
        };
        /** RouteIn */
        RouteIn: {
            /** Proposed Routing */
            proposed_routing?: string | null;
            /** Included */
            included?: boolean | null;
            /** Reason */
            reason: string;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Run Number */
            run_number: string;
            /** State */
            state: string;
            /** Version */
            version: number;
            /** Prompt Version */
            prompt_version: string;
            /** Coverage Start Utc */
            coverage_start_utc: string;
            /** Coverage End Utc */
            coverage_end_utc: string;
            /** Initiated By */
            initiated_by: string;
        };
        /** ScoreIn */
        ScoreIn: {
            /** Nz Relevance */
            nz_relevance?: number | null;
            /** India Relevance */
            india_relevance?: number | null;
            /** Member Relevance */
            member_relevance?: number | null;
            signal?: components["schemas"]["SignalStrength"] | null;
            confidence?: components["schemas"]["SourceConfidence"] | null;
            /** Reason */
            reason: string;
        };
        /** SessionOut */
        SessionOut: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Roles */
            roles: string[];
            /** Csrf Token */
            csrf_token: string;
        };
        /**
         * SignalStrength
         * @enum {string}
         */
        SignalStrength: "Low" | "Medium" | "High" | "Critical";
        /**
         * SourceConfidence
         * @enum {string}
         */
        SourceConfidence: "High" | "Medium" | "Low" | "Unverified";
        /**
         * TransitionIn
         * @description Body shared by all four lifecycle commands. `approval_ref` is optional at the schema level
         *     because only three of the four transitions are human-gated (`complete` is not) - `RunRepository`
         *     is still the sole enforcer of which ones actually require it; this model does not duplicate
         *     that rule.
         */
        TransitionIn: {
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
            /** Approval Ref */
            approval_ref?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationState
         * @enum {string}
         */
        VerificationState: "Verified" | "Partially Verified" | "Unverified" | "Not Required" | "Rejected";
        /** VerifyIn */
        VerifyIn: {
            verification: components["schemas"]["VerificationState"];
            /** Reason */
            reason: string;
            /** Sod Exception Id */
            sod_exception_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs__run_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_run_api_runs__run_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fail_qa_api_runs__run_id__fail_qa_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_run_api_runs__run_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_run_api_runs__run_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_audit_api_runs__run_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
                before_id?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPageOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidates_api_candidates_get: {
        parameters: {
            query: {
                /** @description Run id to list candidates for. */
                run: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"][];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_candidate_api_candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureCandidateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_api_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_candidate_api_candidates__candidate_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_candidate_api_candidates__candidate_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_candidate_api_candidates__candidate_id__route_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_candidate_api_candidates__candidate_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_api_comms_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description No session, or the session has expired or been idle too long. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated and refused: the CSRF token is missing or wrong, the account is no longer active, or the caller does not hold a role permitted this operation. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_api_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    sign_out_api_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    begin_github_sign_in_api_auth_github_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    complete_github_sign_in_api_auth_github_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                inzbc_oauth_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fta_query_api_fta_query_get: {
        parameters: {
            query: {
                /** @description A sector or product question, e.g. 'dairy' or 'manuka honey'. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FtaQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
