-- SIP database schema — v0.1 draft (Postgres)
-- Grounded in the Intelligence Database v1.9 model and the SIP spec (docs/sip/).
-- Contract for Roshan (pipeline) and Paras (UI) to build against. Not yet migrated;
-- the internal-platform decision (AIOS foundation decision 2) may host this differently,
-- but the shape stands. The Intelligence Database is the single Action Register.

-- ---------- controlled vocab (from the workbook's Lookup Values) ----------
create type signal_strength   as enum ('Low','Medium','High','Critical');
create type source_confidence as enum ('High','Medium','Low','Unverified');
create type source_outcome    as enum ('Included','Context','Suppressed','Inaccessible','Excluded','No Qualifying Item');
create type verification_state as enum ('Verified','Partially Verified','Unverified','Not Required','Rejected');
-- approval_state stays: daily_intelligence.approval still uses it for per-item approval.
-- distribution_state is gone with the approvals table it served. ADR-0005 records distribution
-- authority as a decision value, so 'Distributed' and 'Withdrawn' no longer live in two enums.
create type approval_state     as enum ('Pending','Approved','Rejected','Returned for Correction','Superseded');

-- ADR-0005: the three decision facts, and the values each may carry. The kind/value pairing is
-- enforced on decision_records; this enum is only the union of legal values.
create type decision_kind      as enum ('CEO Ruling','Report Approval','Distribution Authority');
create type decision_value     as enum (
  'Continue','Continue With Correction','Pause','Stop',
  'Approved','Rejected','Returned for Correction',
  'Authorised','Not Authorised'
);

create type run_state          as enum (
  'Draft','Run Authorised','Coverage Locked','Scanning','Candidate Review','Report Drafted',
  'QA In Progress','QA Failed','Awaiting CEO Decision','Continue','Continue With Correction',
  'Paused','Stopped','Approved for Manual Distribution','Distributed','Closed','Corrected','Withdrawn'
);

-- ---------- identity ----------
create table roles (
  id   smallint primary key,
  name text not null unique  -- SIP Owner, Analyst, Reviewer, Secretariat, Administrator, Board Viewer, Auditor
);

create table users (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  email         text not null unique,
  -- ADR-0004: GitHub provides authentication only, never authorisation. A successful GitHub
  -- login is matched against this column; no active row means 403 and no session. Nullable
  -- because a service account or a seeded test user has no GitHub identity, and unique so two
  -- rows cannot claim the same login. Authorisation comes from user_roles, never from here.
  github_login  text unique,
  active        boolean not null default true,
  mfa_enabled   boolean not null default false,
  created_at    timestamptz not null default now(),
  last_login_at timestamptz
);

-- One principal may hold any number of roles. ADR-0005 binds separation of duties to the role held
-- at the time of an act, and the three-engineer split is a 16-week placement: the steady state
-- afterwards is one person holding every role. A single users.role_id could not express that.
-- This supersedes the one-column mapping ADR-0004 described; role mapping is still data.
create table user_roles (
  user_id     uuid not null references users(id),
  role_id     smallint not null references roles(id),
  enabled     boolean not null default true,
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

-- Opaque server-side sessions, per ADR-0004. Not JWTs: a stateless token cannot be withdrawn
-- before it expires, and offboarding has to take effect at once. Deleting the row, or setting
-- users.active = false, ends access on the next request.
--
-- `id` is the value in the cookie and is generated by the application from a CSRF-safe random
-- source, not by the database, so the column has no default: a session must be issued
-- deliberately. `csrf_token` backs the double-submit check ADR-0004 requires, because
-- SameSite=Lax alone does not cover top-level POST navigation.
--
-- Two expiries, both from ADR-0004, and the earlier one wins: absolute 12 hours so a stolen
-- cookie cannot live indefinitely, and 60 minutes idle so an unattended session closes itself.
create table sessions (
  id            text primary key,
  user_id       uuid not null references users(id),
  csrf_token    text not null,
  created_at    timestamptz not null default now(),
  last_seen_at  timestamptz not null default now(),
  expires_at    timestamptz not null
);

create index sessions_user_id_idx on sessions (user_id);

-- ---------- production run ----------
create table runs (
  id                    uuid primary key default gen_random_uuid(),
  run_number            text not null unique,          -- RUN-YYYYMMDD-01
  coverage_start_utc    timestamptz not null,
  coverage_end_utc      timestamptz not null,
  coverage_timezone     text not null default 'Pacific/Auckland',
  state                 run_state not null default 'Draft',
  prompt_version        text not null,                 -- e.g. SIP-050 v1.1
  production_enabled    boolean not null default false,
  initiated_by          uuid not null references users(id),
  analyst_id            uuid references users(id),
  reviewer_id           uuid references users(id),      -- must differ from analyst (enforced in app)
  started_at            timestamptz,
  completed_at          timestamptz,
  qa_status             text,
  -- Optimistic concurrency (#117): every state transition does
  -- `UPDATE ... SET version = version + 1 WHERE id = ? AND version = ?`. Zero rows affected means
  -- someone else's transition landed first - the caller must re-read and retry, not silently
  -- overwrite. Two reviewers acting on the same run at once must not both be able to commit.
  version               integer not null default 0,
  created_at            timestamptz not null default now(),
  check (coverage_end_utc > coverage_start_utc),
  check (analyst_id is null or reviewer_id is null or analyst_id <> reviewer_id)
);

-- ---------- source coverage ----------
create table source_library (
  id            uuid primary key default gen_random_uuid(),
  sip185_code   text unique,              -- SIP-185 register id, e.g. 'NZ-OFF-001'; stable, unique.
                                          -- Nullable so an ad-hoc/non-register source can exist,
                                          -- but every SIP-185-backed source MUST carry it at seed
                                          -- time: source-check recording resolves by this code and
                                          -- hard-fails without it (source_register.record_source_outcome).
  name          text not null,            -- display / candidate-capture label only; NOT unique
                                          -- (NZ and India both have a 'Ministry of Defence' and a
                                          -- 'Ministry of Education') - never resolve a source-check by name.
  layer         smallint not null,        -- 1 Official .. 5 Other
  mandatory     boolean not null default false,
  base_url      text,
  fallback_note text,
  active        boolean not null default true
);

create table source_checks (
  id           uuid primary key default gen_random_uuid(),
  run_id       uuid not null references runs(id) on delete cascade,
  source_id    uuid not null references source_library(id),
  checked_at   timestamptz not null default now(),
  method       text,
  outcome      source_outcome not null,
  fallback_used boolean not null default false,
  access_error text,
  notes        text,
  unique (run_id, source_id)
);

-- ---------- candidate + finalised intelligence ----------
create table candidates (
  id                 uuid primary key default gen_random_uuid(),
  run_id             uuid not null references runs(id) on delete cascade,
  source_id          uuid references source_library(id),
  url                text,
  headline           text not null,
  summary            text,
  published_at       timestamptz,
  captured_at        timestamptz not null default now(),
  -- Who performed each act, so separation of duties can be checked against the acts themselves
  -- rather than against role membership. Holding the Reviewer role says a person may review
  -- something; it cannot say whether they are reviewing their own work, and BR8 is about the
  -- latter. Without these columns one principal could capture, score, route and verify the same
  -- candidate end to end while passing every role check, because `require_roles` is an OR over
  -- the roles held and the steady state after the placement is one person holding all of them.
  --
  -- Nullable because rows predating this column cannot have their authorship reconstructed.
  -- A null means "unknown", and verification of an unattributable candidate is permitted: with
  -- these columns nullable there is no way to distinguish "nobody captured this" from "we failed
  -- to record who did", and refusing both would strand every candidate captured before the
  -- column existed. Every candidate written through the API records its capturer, so a null can
  -- only come from a legacy row or a direct SQL insert.
  --
  -- This is a stated trade-off rather than a control. Making these NOT NULL after a backfill is
  -- the change that would turn it into one.
  captured_by        uuid references users(id),
  assessed_by        uuid references users(id),
  verified_by        uuid references users(id),
  in_coverage_window boolean,
  nz_relevance       smallint,   -- 0..5 scores
  india_relevance    smallint,
  member_relevance   smallint,
  signal             signal_strength,
  confidence         source_confidence,
  verification       verification_state not null default 'Unverified',
  duplicate_of       uuid references candidates(id),
  included           boolean,
  reason             text,
  proposed_routing   text
);

create table daily_intelligence (
  id             uuid primary key default gen_random_uuid(),
  run_id         uuid not null references runs(id) on delete cascade,
  candidate_id   uuid references candidates(id),
  rank           smallint,
  headline       text not null,
  what_happened  text,
  why_it_matters text,
  nz_impact      text,
  member_impact  text,
  ceo_action     text,
  member_action  text,
  signal         signal_strength,
  confidence     source_confidence,
  approval       approval_state not null default 'Pending'
);

-- A recorded, deliberate exception to the candidate separation-of-duties rule.
--
-- INZBC is one person holding every role, and that is the steady state rather than a temporary
-- shortage. A control that simply refuses when the capturer is the only available verifier would
-- be switched off within a week, and a switched-off control evidences nothing. This lets the act
-- proceed while recording that it happened, who authorised it and why, which is the honest
-- position: the audit trail says a single person carried the candidate end to end, rather than
-- implying a second party who does not exist.
--
-- Deliberately NOT modelled on `sod_exceptions`: that table is keyed on `report_version_id` and
-- `decision_kind`, so it cannot express an exception about a candidate.
create table candidate_sod_exceptions (
  id            uuid primary key default gen_random_uuid(),
  candidate_id  uuid not null references candidates(id) on delete cascade,
  actor_id      uuid not null references users(id),
  approved_by   uuid not null references users(id),
  approved_at   timestamptz not null default now(),
  reason        text not null check (btrim(reason) <> ''),
  review_date   date not null,
  -- One exception authorises one act, not a standing permission. A second self-verification
  -- needs its own recorded exception.
  unique (candidate_id, actor_id)
);

-- ---------- registers (Intelligence Database is the authority) ----------
create table action_register (
  id             uuid primary key default gen_random_uuid(),
  action_code    text not null unique,      -- ACT-016 ...
  title          text not null,
  description    text,
  owner_id       uuid references users(id),
  owner_text     text,
  priority       text,
  due_date       date,
  review_date    date,
  status         text not null,             -- Open, Closed, Controlled Monitoring, ...
  evidence_ref   text,
  closed_at      timestamptz,
  created_at     timestamptz not null default now()
);

create table watch_lists (
  id            uuid primary key default gen_random_uuid(),
  watch_code    text not null unique,       -- WL-006 ...
  title         text not null,
  category      text,
  frequency     text,
  escalation    text,
  status        text not null,
  next_review   date
);

create table exceptions (
  id            uuid primary key default gen_random_uuid(),
  run_id        uuid references runs(id),
  exception_type text not null,
  severity      text not null,
  owner_id      uuid references users(id),
  status        text not null,
  original_preserved boolean not null default true,
  correction_ref text,
  created_at    timestamptz not null default now()
);

-- ---------- decisions (ADR-0005) ----------
-- The old `approvals` table stored one mutable row per run. It could not tell an explicit CEO
-- "distribution: No" from a run nobody had ruled on (both were the column default), gave a
-- distribution decision no actor or timestamp of its own, and overwrote its own history on
-- correction. SIP-050 s24 forbids overwriting approvals and distribution decisions, and s26 wants
-- an approver, decision, timestamp, conditions and audience recorded per decision. What follows
-- replaces it.

-- Which role may record which decision. With no row for a (kind, role) pair, decision_records' FK
-- has nothing to point at and the insert is refused, so an unconfigured role genuinely cannot
-- decide. Note the FK matches on (kind, actor_role_id) only: `enabled = false` does NOT currently
-- block anything, and the writing command must check it.
create table decision_role_permissions (
  kind          decision_kind not null,
  actor_role_id smallint not null references roles(id),
  enabled       boolean not null default true,
  primary key (kind, actor_role_id)
);

-- "For this decision kind, whoever acts in actor_role_id must be a different person from whoever
-- acted in other_role_id." Configuration, not code, so the staffing change at the end of the
-- placement is a data change.
-- NOT enforced by this schema. Nothing references this table; the only CHECK below says the two
-- role ids differ, which says nothing about whether one person performed both acts. Comparing
-- actors across two decision records is cross-row, so CHECK cannot do it. Until the writing
-- command consults this table, sod_exception_id stays nullable in practice and an unrecorded
-- self-approval is NOT refused, contrary to ADR-0005 Required follow-up 4. Enforcement is
-- follow-up 4's job, not this table's.
create table decision_sod_role_pairs (
  kind          decision_kind not null,
  actor_role_id smallint not null,
  other_role_id smallint not null references roles(id),
  enabled       boolean not null default true,
  primary key (kind, actor_role_id, other_role_id),
  foreign key (kind, actor_role_id) references decision_role_permissions(kind, actor_role_id),
  check (actor_role_id <> other_role_id)
);

-- Deliberately unseeded: client-answers B8 is still PROPOSED.
-- NOT enforced by this schema. Nothing references this table, so an empty row set does NOT by
-- itself stop an Authorised decision being recorded. The release predicate in ADR-0005 Decision 2
-- (current approval Approved, current ruling Continue, no open Critical QA failure, recipient
-- matching this row) spans rows and tables, which CHECK cannot see. It has to be enforced by the
-- single application command that writes a decision, inside the same transaction that advances
-- the stream head. Until that command exists, treat this table as configuration, not a gate.
create table distribution_configuration (
  singleton         boolean primary key default true check (singleton),
  recipient_address text not null check (btrim(recipient_address) <> ''),
  channel           text not null check (btrim(channel) <> ''),
  configured_by     uuid not null references users(id),
  configured_at     timestamptz not null default now()
);

-- A decision binds to an exact artefact. Free text could not: 'v1', '1' and 'v1 final' may all
-- mean one report.
create table report_versions (
  id                 uuid primary key default gen_random_uuid(),
  run_id             uuid not null references runs(id),
  version_number     integer not null check (version_number > 0),
  created_by         uuid not null,
  created_by_role_id smallint not null,
  content_sha256     text not null check (content_sha256 ~ '^[0-9a-f]{64}$'),
  created_at         timestamptz not null,
  submitted_at       timestamptz not null default now(),
  unique (run_id, version_number),
  foreign key (created_by, created_by_role_id) references user_roles(user_id, role_id),
  check (submitted_at >= created_at)
);

-- One stream per (version, kind), opened when the version is submitted. This is what makes
-- absence meaningful: a stream with a null head is submitted-but-undecided, which is a different
-- fact from no stream at all. The head is the only mutable part of the decision model.
create table decision_streams (
  id                uuid primary key default gen_random_uuid(),
  report_version_id uuid not null references report_versions(id),
  kind              decision_kind not null,
  current_record_id uuid,
  head_revision     integer not null default 0,
  opened_at         timestamptz not null default now(),
  unique (report_version_id, kind),
  unique (id, report_version_id, kind),
  check (
    (current_record_id is null and head_revision = 0)
    or (current_record_id is not null and head_revision > 0)
  )
);

-- Where one principal must hold both sides of a required-distinct pair, the decision still
-- commits, but only against a recorded exception. Scoped to the exact version, kind, actor and
-- acting role so it cannot be reused as a blanket waiver.
create table sod_exceptions (
  id                uuid primary key default gen_random_uuid(),
  report_version_id uuid not null references report_versions(id),
  kind              decision_kind not null,
  actor_id          uuid not null,
  actor_role_id     smallint not null,
  approved_by       uuid not null references users(id),
  approved_at       timestamptz not null default now(),
  reason            text not null check (btrim(reason) <> ''),
  review_date       date not null,
  evidence_ref      text,
  unique (id, report_version_id, kind, actor_id, actor_role_id),
  foreign key (actor_id, actor_role_id) references user_roles(user_id, role_id)
);

-- Immutable. Never updated, never deleted; a correction appends a record superseding its
-- predecessor. REQ-U-02's reason, conditions, owner, evidence and next review are mandatory here
-- because a decision without them cannot be audited later.
create table decision_records (
  id                     uuid primary key default gen_random_uuid(),
  stream_id              uuid not null,
  report_version_id      uuid not null,
  kind                   decision_kind not null,
  stream_revision        integer not null check (stream_revision > 0),
  value                  decision_value not null,
  actor_id               uuid not null,
  actor_role_id          smallint not null,
  decided_at             timestamptz not null,
  recorded_at            timestamptz not null default now(),
  reason                 text not null check (btrim(reason) <> ''),
  conditions             text[] not null default '{}',
  owner_id               uuid not null references users(id),
  evidence_ref           text not null check (btrim(evidence_ref) <> ''),
  next_review            date not null,
  distribution_recipient text,
  supersedes_id          uuid,
  sod_exception_id       uuid,
  idempotency_key        uuid not null unique,

  unique (stream_id, stream_revision),
  unique (stream_id, id),
  unique (stream_id, id, stream_revision),
  unique (supersedes_id),
  unique (sod_exception_id),
  unique (id, report_version_id, kind, value, distribution_recipient),

  -- The record cannot claim a stream it does not belong to, or a kind its stream does not carry.
  foreign key (stream_id, report_version_id, kind)
    references decision_streams(id, report_version_id, kind),
  -- Supersession cannot cross streams.
  foreign key (stream_id, supersedes_id) references decision_records(stream_id, id),
  foreign key (actor_id, actor_role_id) references user_roles(user_id, role_id),
  foreign key (kind, actor_role_id) references decision_role_permissions(kind, actor_role_id),
  foreign key (sod_exception_id, report_version_id, kind, actor_id, actor_role_id)
    references sod_exceptions(id, report_version_id, kind, actor_id, actor_role_id),

  check (supersedes_id is null or supersedes_id <> id),
  -- Revision 1 is the only root; every later revision supersedes exactly one predecessor.
  check (
    (stream_revision = 1 and supersedes_id is null)
    or (stream_revision > 1 and supersedes_id is not null)
  ),
  check (
    (kind = 'CEO Ruling' and value in ('Continue','Continue With Correction','Pause','Stop'))
    or (kind = 'Report Approval' and value in ('Approved','Rejected','Returned for Correction'))
    or (kind = 'Distribution Authority' and value in ('Authorised','Not Authorised'))
  ),
  -- Both Yes and No are decisions about a concrete requested recipient.
  check (
    (kind = 'Distribution Authority'
      and distribution_recipient is not null and btrim(distribution_recipient) <> '')
    or (kind <> 'Distribution Authority' and distribution_recipient is null)
  )
);

-- Added after both tables exist. Proves only that the referenced (stream, record, revision) tuple
-- exists and belongs to this stream. It does NOT prove the record is the newest, nor that the head
-- moved forward: this constraint alone still permits moving a head backwards to an earlier
-- revision, or pointing it at any historical record of the same stream. Ordering is the writing
-- command's job — it must compare-and-swap on the existing head, requiring
-- new_revision = old_head_revision + 1 and supersedes_id = old_current_record_id, and abort the
-- whole decision on a zero-row result.
alter table decision_streams
  add constraint decision_streams_current_record_fk
  foreign key (id, current_record_id, head_revision)
  references decision_records(stream_id, id, stream_revision);

-- What was actually sent. Distribution delivery is execution evidence, not an authority state.
-- The composite FK means a delivery can only reference an Authorised authority for the same
-- version and the same recipient; that it is still current is checked in the transaction.
create table distribution_deliveries (
  id                  uuid primary key default gen_random_uuid(),
  authority_record_id uuid not null,
  report_version_id   uuid not null,
  authority_kind      decision_kind not null default 'Distribution Authority'
    check (authority_kind = 'Distribution Authority'),
  authority_value     decision_value not null default 'Authorised'
    check (authority_value = 'Authorised'),
  sender_id           uuid not null references users(id),
  recipient_address   text not null check (btrim(recipient_address) <> ''),
  channel             text not null check (btrim(channel) <> ''),
  sent_at             timestamptz not null,
  delivery_result     text not null check (btrim(delivery_result) <> ''),
  recorded_at         timestamptz not null default now(),
  idempotency_key     uuid not null unique,
  foreign key (authority_record_id, report_version_id, authority_kind, authority_value,
               recipient_address)
    references decision_records(id, report_version_id, kind, value, distribution_recipient)
);

-- The one authoritative combined read. Null value columns mean undecided; 'Not Authorised' is an
-- explicit refusal. Consumers use this rather than each inventing a derivation rule.
create view current_report_decisions as
select
  rv.id   as report_version_id,
  rv.run_id,
  rv.version_number,
  rv.content_sha256,
  rv.submitted_at,
  ruling.value     as ceo_ruling,
  ruling.actor_id  as ceo_ruling_actor_id,
  ruling.decided_at as ceo_ruling_decided_at,
  appr.value       as report_approval,
  appr.actor_id    as report_approval_actor_id,
  appr.decided_at  as report_approval_decided_at,
  auth.value       as distribution_authority,
  auth.actor_id    as distribution_authority_actor_id,
  auth.decided_at  as distribution_authority_decided_at,
  auth.distribution_recipient
from report_versions rv
join decision_streams rs
  on rs.report_version_id = rv.id and rs.kind = 'CEO Ruling'
left join decision_records ruling
  on ruling.id = rs.current_record_id and ruling.stream_id = rs.id
join decision_streams as_
  on as_.report_version_id = rv.id and as_.kind = 'Report Approval'
left join decision_records appr
  on appr.id = as_.current_record_id and appr.stream_id = as_.id
join decision_streams ds
  on ds.report_version_id = rv.id and ds.kind = 'Distribution Authority'
left join decision_records auth
  on auth.id = ds.current_record_id and auth.stream_id = ds.id;

-- Submitting a version opens its three streams, so a decision can never arrive for a stream
-- nobody created.
create function open_decision_streams() returns trigger
language plpgsql as $$
begin
  insert into decision_streams (report_version_id, kind)
  values (new.id, 'CEO Ruling'), (new.id, 'Report Approval'), (new.id, 'Distribution Authority');
  return new;
end;
$$;

create trigger report_version_open_decision_streams
after insert on report_versions
for each row execute function open_decision_streams();

-- Belt and braces against an accidental UPDATE or DELETE. The real boundary is the grants below;
-- a table owner can always re-grant itself privileges, so this catches mistakes, not malice.
create function reject_evidence_change() returns trigger
language plpgsql as $$
begin
  raise exception '% is append-only; % is not allowed', tg_table_name, tg_op
    using errcode = '55000';
end;
$$;

create trigger report_versions_append_only before update or delete on report_versions
  for each row execute function reject_evidence_change();
create trigger sod_exceptions_append_only before update or delete on sod_exceptions
  for each row execute function reject_evidence_change();
-- Same protection for the candidate-level exceptions: an exception that can be edited after the
-- act it authorised is not evidence of anything.
create trigger candidate_sod_exceptions_append_only
  before update or delete on candidate_sod_exceptions
  for each row execute function reject_evidence_change();
create trigger decision_records_append_only before update or delete on decision_records
  for each row execute function reject_evidence_change();
create trigger distribution_deliveries_append_only before update or delete on distribution_deliveries
  for each row execute function reject_evidence_change();

-- A row trigger never fires for a whole-table wipe, so every guard above could be walked past in
-- one statement. The restricted application role has no such privilege, but these triggers are
-- described as catching a mistake by the table owner or a migration, and that is precisely who
-- runs one. Only a statement-level trigger sees it.
create trigger report_versions_no_wipe before truncate on report_versions
  for each statement execute function reject_evidence_change();
create trigger sod_exceptions_no_wipe before truncate on sod_exceptions
  for each statement execute function reject_evidence_change();
create trigger decision_records_no_wipe before truncate on decision_records
  for each statement execute function reject_evidence_change();
create trigger distribution_deliveries_no_wipe before truncate on distribution_deliveries
  for each statement execute function reject_evidence_change();

-- Grants are intentionally not applied here: the application login role is provisioned outside
-- this file (see database/audit_role.sql), and CI applies this schema with no such role existing.
-- When it does exist, the decision tables get SELECT and INSERT only, decision_streams gets
-- UPDATE (current_record_id, head_revision) and nothing else, and audit_log gets INSERT and SELECT
-- only. That grant is the real append-only boundary for audit_log; the trigger below catches a
-- mistake by a role that can still UPDATE/DELETE (a migration, or the table owner).

-- ---------- append-only audit ----------
-- Immutable by database rule, not by application convention (#118). A mutation writes its audit row
-- (old_value/new_value/reason/approval_ref) inside its own transaction via services/api/audit.py, so
-- the state change and its audit record commit together or not at all. Nothing may later rewrite or
-- erase that record: the app login role is granted INSERT/SELECT only (database/audit_role.sql), and
-- the trigger below refuses UPDATE/DELETE from any role, reusing the same reject_evidence_change()
-- guard the decision tables use.
create table audit_log (
  id           bigserial primary key,
  at           timestamptz not null default now(),
  user_id      uuid references users(id),
  action       text not null,
  record_type  text,
  record_id    text,
  old_value    text,
  new_value    text,
  reason       text,
  approval_ref text
);

create trigger audit_log_append_only before update or delete on audit_log
  for each row execute function reject_evidence_change();
create trigger audit_log_no_wipe before truncate on audit_log
  for each statement execute function reject_evidence_change();
