"""Generates docs/fta-corpus-report.md from apps/fta/corpus.py's actual data (#337).

Reads CORPUS directly rather than restating counts by hand, so the report cannot drift from the
corpus the Explainer actually queries. Rerun after any corpus.py change:

    python -m scripts.fta_corpus_report

No `review_after_days` value is written into corpus.py or picked here as a default: INZBC has not
set a review cadence (see corpus.py's `stale_entries()` docstring). The report shows the staleness
picture at three illustrative cutoffs instead of asserting a policy number that doesn't exist yet.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from apps.fta.corpus import CORPUS, SECTORS_IN_SCOPE, TIER_1_SOURCES, stale_entries  # noqa: E402

_OUT = Path(__file__).resolve().parents[1] / "docs" / "fta-corpus-report.md"
_ILLUSTRATIVE_WINDOWS_DAYS = (30, 60, 90)


def build_report(as_of: date) -> str:
    total = len(CORPUS)
    confirmed = [e for e in CORPUS if e.confirmed]
    tier1_confirmed = [e for e in confirmed if e.source_tier == 1]
    unconfirmed = [e for e in CORPUS if not e.confirmed]
    blocked_sources = [s for s in TIER_1_SOURCES if s.automated_fetch_blocked]

    lines: list[str] = []
    lines.append("# FTA corpus coverage and freshness")
    lines.append("")
    lines.append(
        f"Generated by `scripts/fta_corpus_report.py` from `apps/fta/corpus.py` as of "
        f"{as_of.isoformat()}. Rerun the script after any corpus change; do not hand-edit this "
        f"file."
    )
    lines.append("")
    lines.append("## Coverage")
    lines.append("")
    lines.append(f"- Total facts in `CORPUS`: **{total}**")
    lines.append(
        f"- Confirmed (`confirmed=True`): **{len(confirmed)}** ({len(unconfirmed)} not confirmed)"
    )
    lines.append(
        f"- Confirmed and Tier 1 sourced: **{len(tier1_confirmed)}** "
        f"({len(confirmed) - len(tier1_confirmed)} confirmed but Tier 2/secondary)"
    )
    lines.append("")
    lines.append("### By sector (`SECTORS_IN_SCOPE`)")
    lines.append("")
    lines.append("| Sector | Facts | Confirmed | Tier 1 confirmed |")
    lines.append("| --- | --- | --- | --- |")
    for sector in SECTORS_IN_SCOPE:
        sector_entries = [e for e in CORPUS if e.sector == sector]
        sector_confirmed = [e for e in sector_entries if e.confirmed]
        sector_tier1 = [e for e in sector_confirmed if e.source_tier == 1]
        lines.append(
            f"| {sector} | {len(sector_entries)} | {len(sector_confirmed)} | {len(sector_tier1)} |"
        )
    other_sectors = sorted({e.sector for e in CORPUS} - set(SECTORS_IN_SCOPE))
    if other_sectors:
        lines.append("")
        lines.append(
            f"Sectors present in `CORPUS` but not yet in `SECTORS_IN_SCOPE`: {', '.join(other_sectors)}."
        )
    lines.append("")
    lines.append("### Not confirmed")
    lines.append("")
    if unconfirmed:
        for entry in unconfirmed:
            lines.append(
                f"- `{entry.id}` {entry.topic}: {entry.notes or entry.citation}"
            )
    else:
        lines.append("None.")
    lines.append("")
    lines.append("## India-side sources blocked from automated fetch")
    lines.append("")
    lines.append(
        "These Tier 1 sources return 403/bot-protection to automated access as of the date noted "
        "on each; any figure that depends on them must be confirmed by opening the link manually "
        "before it is cited (see `FTA-003`, which is held unconfirmed for exactly this reason)."
    )
    lines.append("")
    for source in blocked_sources:
        lines.append(f"- **{source.name}** — {source.url}")
        if source.note:
            lines.append(f"  {source.note}")
    lines.append("")
    lines.append("## Freshness rule")
    lines.append("")
    lines.append(
        "`stale_entries(entries, as_of, review_after_days)` flags any entry whose `verified_at` "
        "is more than `review_after_days` before `as_of`. **`review_after_days` has no default and "
        "no INZBC-approved value exists yet** — this is a business decision, not a code gap (see "
        "`apps/fta/corpus.py`'s `stale_entries()` docstring). The table below is illustrative only, "
        "computed at three candidate cutoffs, so a reader can see what the mechanism does without "
        "treating any of the three as the adopted policy."
    )
    lines.append("")
    lines.append("| review_after_days (illustrative) | Stale entries | Which |")
    lines.append("| --- | --- | --- |")
    for window in _ILLUSTRATIVE_WINDOWS_DAYS:
        stale = stale_entries(CORPUS, as_of, window)
        ids = ", ".join(f"`{e.id}`" for e in stale) if stale else "none"
        lines.append(f"| {window} | {len(stale)} | {ids} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    report = build_report(date.today())
    _OUT.write_text(report, encoding="utf-8")
    print(f"wrote {_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
